"""
Telegram channel scraper for Xiaomi/HyperOS APK files.

Connects to Telegram via Telethon (MTProto) using a StringSession,
iterates messages from configured channels, filters for APK documents,
downloads new files, and extracts region info from captions.
"""

from __future__ import annotations

import logging
import os
import re
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

from telethon import TelegramClient
from telethon.sessions import StringSession
from telethon.tl.types import InputMessagesFilterDocument

logger = logging.getLogger(__name__)

# Channels to monitor
CHANNELS = [
    "hyperossystemapps",
    "MiuiSystemUpdater",
    "HyperOsUpdates",
]

# Directory to download APKs into
DOWNLOADS_DIR = Path(__file__).resolve().parent.parent / "downloads"

# Region detection patterns (order matters — first match wins)
_REGION_PATTERNS: list[tuple[str, re.Pattern]] = [
    ("china", re.compile(r"\b(china|cn|chinese)\b", re.IGNORECASE)),
    ("global", re.compile(r"\b(global|mi|international)\b", re.IGNORECASE)),
    ("eea", re.compile(r"\b(eea|europe|eu)\b", re.IGNORECASE)),
    ("india", re.compile(r"\b(india|in)\b", re.IGNORECASE)),
    ("indonesia", re.compile(r"\b(indonesia|id)\b", re.IGNORECASE)),
    ("russia", re.compile(r"\b(russia|ru)\b", re.IGNORECASE)),
    ("turkey", re.compile(r"\b(turkey|tr)\b", re.IGNORECASE)),
    ("taiwan", re.compile(r"\b(taiwan|tw)\b", re.IGNORECASE)),
    ("japan", re.compile(r"\b(japan|jp)\b", re.IGNORECASE)),
    ("korea", re.compile(r"\b(korea|kr)\b", re.IGNORECASE)),
    ("poco", re.compile(r"\b(poco)\b", re.IGNORECASE)),
    ("beta", re.compile(r"\b(beta)\b", re.IGNORECASE)),
    ("port", re.compile(r"\b(port|ported)\b", re.IGNORECASE)),
]


@dataclass
class DownloadedApk:
    """Represents a downloaded APK with its Telegram context."""

    file_path: Path
    file_name: str
    file_size: int
    channel: str
    message_id: int
    date: datetime
    caption: str | None
    region: str


def create_client() -> TelegramClient:
    """Create a Telethon client using environment variables.

    Required env vars:
        TELEGRAM_API_ID: Numeric API ID from my.telegram.org
        TELEGRAM_API_HASH: API hash from my.telegram.org
        TELEGRAM_STRING_SESSION: StringSession generated by generate_session.py
    """
    api_id = int(os.environ["TELEGRAM_API_ID"])
    api_hash = os.environ["TELEGRAM_API_HASH"]
    string_session = os.environ["TELEGRAM_STRING_SESSION"]

    return TelegramClient(StringSession(string_session), api_id, api_hash)


def detect_region(caption: str | None, file_name: str | None) -> str:
    """Detect the APK region/variant from message caption and filename.

    Checks both the caption text and the filename for region indicators.
    Returns 'unknown' if no region can be determined.
    """
    # Combine caption and filename for searching
    text = ""
    if caption:
        text += caption
    if file_name:
        text += " " + file_name

    if not text.strip():
        return "unknown"

    for region_name, pattern in _REGION_PATTERNS:
        if pattern.search(text):
            return region_name

    return "unknown"


def _is_apk(message) -> bool:
    """Check if a Telegram message contains an APK file."""
    if not message.file:
        return False

    file_name = message.file.name or ""
    mime_type = message.file.mime_type or ""

    return (
        file_name.lower().endswith(".apk")
        or mime_type == "application/vnd.android.package-archive"
    )


@dataclass
class ApkMessageItem:
    """Represents an APK message candidate from Telegram before downloading."""

    message: Any
    channel: str
    file_name: str
    file_size: int
    region: str


async def get_channel_latest_id(client: TelegramClient, channel_username: str) -> int:
    """Get the absolute newest message ID in a channel."""
    try:
        latest_msgs = await client.get_messages(channel_username, limit=1)
        if latest_msgs:
            return latest_msgs[0].id
    except Exception as exc:
        logger.warning("Could not fetch latest message tip for @%s: %s", channel_username, exc)
    return 0


async def iter_channel_apk_messages(
    client: TelegramClient,
    channel_username: str,
    min_id: int = 0,
    limit: int = 10,
):
    """Iterate over APK document messages in a channel without downloading upfront.

    Yields ApkMessageItem objects.
    """
    effective_limit = limit

    logger.info(
        "Checking @%s (min_id=%d, limit=%d)",
        channel_username, min_id, effective_limit,
    )

    try:
        iter_kwargs = {
            "limit": effective_limit,
            "filter": InputMessagesFilterDocument,
        }
        if min_id > 0:
            iter_kwargs["min_id"] = min_id

        async for message in client.iter_messages(channel_username, **iter_kwargs):
            if not _is_apk(message):
                continue

            file_name = message.file.name or f"app_{message.id}.apk"
            file_size = message.file.size or 0
            region = detect_region(message.text, file_name)

            yield ApkMessageItem(
                message=message,
                channel=channel_username,
                file_name=file_name,
                file_size=file_size,
                region=region,
            )

    except Exception as exc:
        logger.error("Error checking @%s: %s", channel_username, exc)


async def download_apk_file(message, file_name: str) -> Path:
    """Download a single APK from a Telegram message."""
    DOWNLOADS_DIR.mkdir(parents=True, exist_ok=True)
    target_path = DOWNLOADS_DIR / file_name
    await message.download_media(file=str(target_path))
    return target_path
