"""
Telegram channel scraper for Xiaomi/HyperOS APK files.

Connects to Telegram via Telethon (MTProto) using a StringSession,
iterates messages from configured channels, filters for APK documents,
downloads new files, and extracts region info from captions.
"""

from __future__ import annotations

import logging
import os
import re
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

from telethon import TelegramClient
from telethon.sessions import StringSession
from telethon.tl.types import InputMessagesFilterDocument

logger = logging.getLogger(__name__)

# Channels to monitor
CHANNELS = [
    "hyperossystemapps",
    "MiuiSystemUpdater",
    "HyperOsUpdates",
]

# Directory to download APKs into
DOWNLOADS_DIR = Path(__file__).resolve().parent.parent / "downloads"

# Region detection patterns (order matters — first match wins)
_REGION_PATTERNS: list[tuple[str, re.Pattern]] = [
    ("china", re.compile(r"\b(china|cn|chinese)\b", re.IGNORECASE)),
    ("global", re.compile(r"\b(global|mi|international)\b", re.IGNORECASE)),
    ("eea", re.compile(r"\b(eea|europe|eu)\b", re.IGNORECASE)),
    ("india", re.compile(r"\b(india|in)\b", re.IGNORECASE)),
    ("indonesia", re.compile(r"\b(indonesia|id)\b", re.IGNORECASE)),
    ("russia", re.compile(r"\b(russia|ru)\b", re.IGNORECASE)),
    ("turkey", re.compile(r"\b(turkey|tr)\b", re.IGNORECASE)),
    ("taiwan", re.compile(r"\b(taiwan|tw)\b", re.IGNORECASE)),
    ("japan", re.compile(r"\b(japan|jp)\b", re.IGNORECASE)),
    ("korea", re.compile(r"\b(korea|kr)\b", re.IGNORECASE)),
    ("poco", re.compile(r"\b(poco)\b", re.IGNORECASE)),
    ("beta", re.compile(r"\b(beta)\b", re.IGNORECASE)),
    ("port", re.compile(r"\b(port|ported)\b", re.IGNORECASE)),
]


@dataclass
class DownloadedApk:
    """Represents a downloaded APK with its Telegram context."""

    file_path: Path
    file_name: str
    file_size: int
    channel: str
    message_id: int
    date: datetime
    caption: str | None
    region: str


def create_client() -> TelegramClient:
    """Create a Telethon client using environment variables.

    Required env vars:
        TELEGRAM_API_ID: Numeric API ID from my.telegram.org
        TELEGRAM_API_HASH: API hash from my.telegram.org
        TELEGRAM_STRING_SESSION: StringSession generated by generate_session.py
    """
    api_id = int(os.environ["TELEGRAM_API_ID"])
    api_hash = os.environ["TELEGRAM_API_HASH"]
    string_session = os.environ["TELEGRAM_STRING_SESSION"]

    return TelegramClient(StringSession(string_session), api_id, api_hash)


def detect_region(caption: str | None, file_name: str | None) -> str:
    """Detect the APK region/variant from message caption and filename.

    Checks both the caption text and the filename for region indicators.
    Returns 'unknown' if no region can be determined.
    """
    # Combine caption and filename for searching
    text = ""
    if caption:
        text += caption
    if file_name:
        text += " " + file_name

    if not text.strip():
        return "unknown"

    for region_name, pattern in _REGION_PATTERNS:
        if pattern.search(text):
            return region_name

    return "unknown"


def _is_apk(message) -> bool:
    """Check if a Telegram message contains an APK file."""
    if not message.file:
        return False

    file_name = message.file.name or ""
    mime_type = message.file.mime_type or ""

    return (
        file_name.lower().endswith(".apk")
        or mime_type == "application/vnd.android.package-archive"
    )


async def scrape_channel(
    client: TelegramClient,
    channel_username: str,
    min_id: int = 0,
    limit: int = 100,
) -> list[DownloadedApk]:
    """Scrape a single Telegram channel for new APK files.

    Args:
        client: Connected Telethon client.
        channel_username: Channel username (without @).
        min_id: Only fetch messages with ID greater than this.
                Used to skip already-processed messages.
        limit: Maximum number of messages to fetch per channel.

    Returns:
        List of DownloadedApk objects for successfully downloaded files.
    """
    DOWNLOADS_DIR.mkdir(parents=True, exist_ok=True)
    downloaded = []

    logger.info(
        "Scraping @%s (min_id=%d, limit=%d)", channel_username, min_id, limit
    )

    try:
        message_count = 0
        async for message in client.iter_messages(
            channel_username,
            limit=limit,
            min_id=min_id,
            filter=InputMessagesFilterDocument,
        ):
            message_count += 1

            if not _is_apk(message):
                continue

            file_name = message.file.name
            file_size = message.file.size or 0

            # Detect region from caption and filename
            region = detect_region(message.text, file_name)

            logger.info(
                "Found APK: %s (%.2f MB, region=%s) in @%s [msg #%d]",
                file_name,
                file_size / (1024 * 1024),
                region,
                channel_username,
                message.id,
            )

            # Download the APK
            try:
                target_path = DOWNLOADS_DIR / file_name
                await message.download_media(file=str(target_path))

                downloaded.append(
                    DownloadedApk(
                        file_path=target_path,
                        file_name=file_name,
                        file_size=file_size,
                        channel=channel_username,
                        message_id=message.id,
                        date=message.date,
                        caption=message.text,
                        region=region,
                    )
                )
                logger.info("Downloaded: %s", target_path)

            except Exception as exc:
                logger.error(
                    "Failed to download %s from @%s: %s",
                    file_name,
                    channel_username,
                    exc,
                )

        logger.info(
            "Finished @%s: scanned %d messages, downloaded %d APKs",
            channel_username,
            message_count,
            len(downloaded),
        )

    except Exception as exc:
        logger.error("Error scraping @%s: %s", channel_username, exc)

    return downloaded


async def scrape_all_channels(
    client: TelegramClient,
    channel_states: dict[str, int],
    limit: int = 100,
) -> tuple[list[DownloadedApk], dict[str, int]]:
    """Scrape all configured channels for new APK files.

    Args:
        client: Connected Telethon client.
        channel_states: Dict mapping channel username -> last processed message_id.
        limit: Max messages to fetch per channel.

    Returns:
        Tuple of (all_downloaded_apks, updated_channel_states).
    """
    all_downloaded: list[DownloadedApk] = []
    updated_states: dict[str, int] = dict(channel_states)

    for channel in CHANNELS:
        min_id = channel_states.get(channel, 0)
        apks = await scrape_channel(client, channel, min_id=min_id, limit=limit)

        all_downloaded.extend(apks)

        # Update state to the highest message_id seen
        if apks:
            max_msg_id = max(apk.message_id for apk in apks)
            updated_states[channel] = max(updated_states.get(channel, 0), max_msg_id)

    logger.info(
        "Total: downloaded %d new APKs from %d channels",
        len(all_downloaded),
        len(CHANNELS),
    )
    return all_downloaded, updated_states
